# Use the official MongoDB image as the base image
FROM mongo

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Expose the MongoDB port
EXPOSE 27017

# Define the command to run when the container starts
CMD ["mongod", "--quiet"]
