version: "3.8"

services:
  frontend:
    build:
      context: ./workshop_inventory_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./workshop_inventory_backend
    ports:
      - "5000:5000"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=workshop_inventory
    volumes:
      - /dev/shm:/dev/shm

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Mount init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"

networks:
  default:
    driver: bridge
